appink/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^calcu/$', 'calculator.cal.views.calcu',name='calcu'),
    #url(r'^tinymce/', include('tinymce.urls')),
    #url(r'^accounts/', include('allauth.urls')),
    url(r'^multichoice/', include('multichoice.urls')),
    url(r'^q/', include('quiz.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^mathematics/', include('mathematics.urls', namespace="mathematics" )),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*?', include('mathematics.urls', namespace="mathematics" )),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cal/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   url(r'^calcu/$', 'calculator.cal.views.calcu',name='calcu'),
   
)

pageink/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mathematics/', include('mathematics.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*?', include('mathematics.urls')),
]

quiz/urls.py
from django.conf.urls import patterns, url

from .views import QuizListView, CategoriesListView,\
    ViewQuizListByCategory, QuizUserProgressView, QuizMarkingList,\
    QuizMarkingDetail, QuizDetailView, QuizTake


urlpatterns = patterns('',

                       url(regex=r'^$',
                           view=QuizListView.as_view(),
                           name='quiz_index'),

                       url(regex=r'^category/$',
                           view=CategoriesListView.as_view(),
                           name='quiz_category_list_all'),

                       url(regex=r'^category/(?P<category_name>[\w.-]+)/$',
                           view=ViewQuizListByCategory.as_view(),
                           name='quiz_category_list_matching'),

                       url(regex=r'^progress/$',
                           view=QuizUserProgressView.as_view(),
                           name='quiz_progress'),

                       url(regex=r'^marking/$',
                           view=QuizMarkingList.as_view(),
                           name='quiz_marking'),

                       url(regex=r'^marking/(?P<pk>[\d.]+)/$',
                           view=QuizMarkingDetail.as_view(),
                           name='quiz_marking_detail'),

                       #  passes variable 'quiz_name' to quiz_take view
                       url(regex=r'^(?P<slug>[\w-]+)/$',
                           view=QuizDetailView.as_view(),
                           name='quiz_start_page'),

                       url(regex=r'^(?P<quiz_name>[\w-]+)/take/$',
                           view=QuizTake.as_view(),
                           name='quiz_question'),
)

multichoice/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.db import models
from quiz.models import Question


ANSWER_ORDER_OPTIONS = (
    ('content', _('Content')),
    ('random', _('Random')),
    ('none', _('None'))
)


class MCQuestion(Question):

    answer_order = models.CharField(
        max_length=30, null=True, blank=True,
        choices=ANSWER_ORDER_OPTIONS,
        help_text=_("The order in which multichoice "
                    "answer options are displayed "
                    "to the user"),
        verbose_name=_("Answer Order"))

    def check_if_correct(self, guess):
        answer = Answer.objects.get(id=guess)

        if answer.correct is True:
            return True
        else:
            return False

    def order_answers(self, queryset):
        if self.answer_order == 'content':
            return queryset.order_by('content')
        if self.answer_order == 'random':
            return queryset.order_by('?')
        if self.answer_order == 'none':
            return queryset.order_by()
        return queryset

    def get_answers(self):
        return self.order_answers(Answer.objects.filter(question=self))

    def get_answers_list(self):
        return [(answer.id, answer.content) for answer in
                self.order_answers(Answer.objects.filter(question=self))]

    def answer_choice_to_string(self, guess):
        return Answer.objects.get(id=guess).content

    class Meta:
        verbose_name = _("Multiple Choice Question")
        verbose_name_plural = _("Multiple Choice Questions")


@python_2_unicode_compatible
class Answer(models.Model):
    question = models.ForeignKey(MCQuestion, verbose_name=_("Question"))

    content = models.TextField(max_length=1000,
                               blank=False,
                               help_text=_("Enter the answer text that "
                                           "you want displayed"),
                               verbose_name=_("Content"))

    correct = models.BooleanField(blank=False,
                                  default=False,
                                  help_text=_("Is this a correct answer?"),
                                  verbose_name=_("Correct"))

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = _("Answer")
        verbose_name_plural = _("Answers")

physics/models.py
from django.db import models

# Create your models here.





class Question(models.Model):
	Question = models.TextField()
	#Option = models.ForeignKey(Option)
	#Hint = models.ForeignKey(Hint)
	#Solution = models.ForeignKey(Solution)


	def __unicode__(self):
		return self.Question
class Option(models.Model):
	Question = models.ForeignKey(Question)
	Option = models.TextField()

class Hint(models.Model):
	Question = models.ForeignKey(Question)
	Hint = models.TextField()

class Solution(models.Model):
	Question = models.ForeignKey(Question)
	Solution = models.TextField()

quiz/models.py
from __future__ import unicode_literals
import re
import json

from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator
from django.utils.translation import ugettext as _
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible
from django.conf import settings

from model_utils.managers import InheritanceManager


class CategoryManager(models.Manager):

    def new_category(self, category):
        new_category = self.create(category=re.sub('\s+', '-', category)
                                   .lower())

        new_category.save()
        return new_category

class Course(models.Model):

    course = models.CharField(
        verbose_name=_("Course"),
        max_length=250, blank=True, null=True)


    objects = CategoryManager()

    class Meta:
        verbose_name = _("Course")
        verbose_name_plural = _("Courses")

    def __str__(self):
        return self.course
        
@python_2_unicode_compatible
class Category(models.Model):

    category = models.CharField(
        verbose_name=_("Category"),
        max_length=250, blank=True,
        unique=True, null=True)
    course = models.ForeignKey(
        Course, null=True, blank=True,
        verbose_name=_("Course"))
    objects = CategoryManager()

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")

    def __str__(self):
        return self.category


@python_2_unicode_compatible
class SubCategory(models.Model):

    sub_category = models.CharField(
        verbose_name=_("Sub-Category"),
        max_length=250, blank=True, null=True)

    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"))
    course = models.ForeignKey(
        Course, null=True, blank=True,
        verbose_name=_("Course"))

    objects = CategoryManager()

    class Meta:
        verbose_name = _("Sub-Category")
        verbose_name_plural = _("Sub-Categories")

    def __str__(self):
        return self.sub_category + " (" + self.category.category + ")"
@python_2_unicode_compatible
class Goal(models.Model):
    goal = models.CharField(
        verbose_name=_("Goal"),
        max_length=250, blank=True, null=True)
    course = models.ForeignKey(
        Course, null=True, blank=True,
        verbose_name=_("Category"))
    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"))

    sub_category = models.ForeignKey(
        SubCategory, null=True, blank=True,
        verbose_name=_("SubCategory"))


    objects = CategoryManager()

    class Meta:
        verbose_name = _("Goal")
        verbose_name_plural = _("Goals")

    def __str__(self):
        return self.goal + " (" + self.category.category + ")"


@python_2_unicode_compatible
class Quiz(models.Model):

    title = models.CharField(
        verbose_name=_("Title"),
        max_length=60, blank=False)

    description = models.TextField(
        verbose_name=_("Description"),
        blank=True, help_text=_("a description of the quiz"))

    url = models.SlugField(
        max_length=60, blank=False,
        help_text=_("a user friendly url"),
        verbose_name=_("user friendly url"))
    course = models.ForeignKey(
        Course, null=True, blank=True,
        verbose_name=_("Course"))


    category = models.ForeignKey(
        Category, null=True, blank=True,
        verbose_name=_("Category"))
    
    sub_category = models.ForeignKey(
        SubCategory, null=True, blank=True,
        verbose_name=_("SubCategory"))
    
    goal = models.ForeignKey(
        Goal, null=True, blank=True,
        verbose_name=_("Goal"))
    

    random_order = models.BooleanField(
        blank=False, default=False,
        verbose_name=_("Random Order"),
        help_text=_("Display the questions in "
                    "a random order or as they "
                    "are set?"))

    max_questions = models.PositiveIntegerField(
        blank=True, null=True, verbose_name=_("Max Questions"),
        help_text=_("Number of questions to be answered on each attempt."))

    answers_at_end = models.BooleanField(
        blank=False, default=False,
        help_text=_("Correct answer is NOT shown after question."
                    " Answers displayed at the end."),
        verbose_name=_("Answers at end"))

    exam_paper = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, the result of each"
                    " attempt by a user will be"
                    " stored. Necessary for marking."),
        verbose_name=_("Exam Paper"))

    single_attempt = models.BooleanField(
        blank=False, default=False,
        help_text=_("If yes, only one attempt by"
                    " a user will be permitted."
                    " Non users cannot sit this exam."),
        verbose_name=_("Single Attempt"))

    pass_mark = models.SmallIntegerField(
        blank=True, default=0,
        help_text=_("Percentage required to pass exam."),
        validators=[MaxValueValidator(100)])

    success_text = models.TextField(
        blank=True, help_text=_("Displayed if user passes."),
        verbose_name=_("Success Text"))

    fail_text = models.TextField(
        verbose_name=_("Fail Text"),
        blank=True, help_text=_("Displayed if user fails."))

    draft = models.BooleanField(
        blank=True, default=False,
        verbose_name=_("Draft"),
        help_text=_("If yes, the quiz is not displayed"
                    " in the quiz list and can only be"
                    " taken by users who can edit"
                    " quizzes."))

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        self.url = re.sub('\s+', '-', self.url).lower()

        self.url = ''.join(letter for letter in self.url if
                           letter.isalnum() or letter == '-')

        if self.single_attempt is True:
            self.exam_paper = True

        if self.pass_mark > 100:
            raise ValidationError('%s is above 100' % self.pass_mark)

        super(Quiz, self).save(force_insert, force_update, *args, **kwargs)

    class Meta:
        verbose_name = _("Quiz")
        verbose_name_plural = _("Quizzes")

    def __str__(self):
        return self.title

    def get_questions(self):
        return self.question_set.all().select_subclasses()

    @property
    def get_max_score(self):
        return self.get_questions().count()

    def anon_score_id(self):
        return str(self.id) + "_score"

    def anon_q_list(self):
        return str(self.id) + "_q_list"

    def anon_q_data(self):
        return str(self.id) + "_data"


class ProgressManager(models.Manager):

    def new_progress(self, user):
        new_progress = self.create(user=user,
                                   score="")
        new_progress.save()
        return new_progress


class Progress(models.Model):
    """
    Progress is used to track an individual signed in users score on different
    quiz's and categories

    Data stored in csv using the format:
        category, score, possible, category, score, possible, ...
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, verbose_name=_("User"))

    score = models.CommaSeparatedIntegerField(max_length=1024,
                                              verbose_name=_("Score"))

    objects = ProgressManager()

    class Meta:
        verbose_name = _("User Progress")
        verbose_name_plural = _("User progress records")

    @property
    def list_all_cat_scores(self):
        """
        Returns a dict in which the key is the category name and the item is
        a list of three integers.

        The first is the number of questions correct,
        the second is the possible best score,
        the third is the percentage correct.

        The dict will have one key for every category that you have defined
        """
        score_before = self.score
        output = {}

        for cat in Category.objects.all():
            to_find = re.escape(cat.category) + r",(\d+),(\d+),"
            #  group 1 is score, group 2 is highest possible

            match = re.search(to_find, self.score, re.IGNORECASE)

            if match:
                score = int(match.group(1))
                possible = int(match.group(2))

                try:
                    percent = int(round((float(score) / float(possible))
                                        * 100))
                except:
                    percent = 0

                output[cat.category] = [score, possible, percent]

            else:  # if category has not been added yet, add it.
                self.score += cat.category + ",0,0,"
                output[cat.category] = [0, 0]

        if len(self.score) > len(score_before):
            # If a new category has been added, save changes.
            self.save()

        return output

    def update_score(self, question, score_to_add=0, possible_to_add=0):
        """
        Pass in question object, amount to increase score
        and max possible.

        Does not return anything.
        """
        category_test = Category.objects.filter(category=question.category)\
                                        .exists()

        if any([item is False for item in [category_test,
                                           score_to_add,
                                           possible_to_add,
                                           isinstance(score_to_add, int),
                                           isinstance(possible_to_add, int)]]):
            return _("error"), _("category does not exist or invalid score")

        to_find = re.escape(str(question.category)) +\
            r",(?P<score>\d+),(?P<possible>\d+),"

        match = re.search(to_find, self.score, re.IGNORECASE)

        if match:

quiz/forms.py
from django import forms
from django.forms.widgets import RadioSelect, Textarea


class QuestionForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        choice_list = [x for x in question.get_answers_list()]
        self.fields["answers"] = forms.ChoiceField(choices=choice_list,
                                                   widget=RadioSelect)


class EssayForm(forms.Form):
    def __init__(self, question, *args, **kwargs):
        super(EssayForm, self).__init__(*args, **kwargs)
        self.fields["answers"] = forms.CharField(
            widget=Textarea(attrs={'style': 'width:100%'}))

multichoice/templates/quiz/chemistry_question_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Chemistry Subcategory" %}</h1>

        {% for subcategory in subcategory_list %}

  			
			  <h2>{{ subcategory.sub_category }}</h2>
        {% endfor %}

{% endblock %}

multichoice/templates/quiz/course_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Courses" %}</h1>

        {% for course in course_list %}

<table border="1" style="width:100%">
  <tr>
    <td><a href="/multichoice/{{ course.course }}"> {{ course.course }} </a></td>

  </tr>
</table>
			  
  
        {% endfor %}
{% endblock %}

multichoice/templates/quiz/mathematics_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of MCQuestions" %}</h1>

        {% for mcquestion in mcquestion_list %}

  			
			  <h2>{{ mcquestion.category }}</h2>
			  <h3>{{ mcquestion.sub_category }}</h3>
			  <p>{{ mcquestion.content }}</p>
			  
			  {% for answer in mcquestion.answer_set.all %}

  			
			  <p>{{ answer.content }}</p>
        {% endfor %}

<p>{{ mcquestion.explanation }}</p>

        {% endfor %}

{% endblock %}

multichoice/templates/quiz/mathematics_question_list (copy).html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of ddfMCQuestions" %}</h1>

        {% for mcquestion in mcquestion_list %}

  			
			  <h2>{{ mcquestion.category }}</h2>
			  <h3>{{ mcquestion.sub_category }}</h3>
			  <p>{{ mcquestion.content }}</p>
             
         {% if mcquestion.figure %}
    <img src="{{ mcquestion.figure.url }}" alt="{{ mcquestion.content }} height="100" width="100"" />
         {% endif %}
		  
{% for answer in mcquestion.answer_set.all %}

  			
			  <p>{{ answer.content }}</p>
        {% endfor %}

<p>{{ mcquestion.explanation }}</p>

        {% endfor %}

{% endblock %}

multichoice/templates/quiz/mathematics_question_list1.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Sub Topics" %}</h1>
        {% for goal in goal_list %}
        
<table border="1" style="width:100%">
  <td>
        
       <tr> <a href="/multichoice/{{ goal.course }}/{{ goal.category }}/{{ goal.sub_category }}/{{ goal.goal }}">{{ goal.goal }}</a><tr>
  </td>
</table>      
        {% endfor %}


{% for mcquestion in mcquestion_list %}
  			
			  <h4>Subject: {{ mcquestion.category }}</h4>
			  <h6>Topic: {{ mcquestion.sub_category }}</h6>
			  <h6>Goal: {{ mcquestion.goal }}</h6>
			  <p><b>Question: </b> {{ mcquestion.content }}</p>
             
         {% if mcquestion.figure %}
    <img src="{{ mcquestion.figure.url }}" alt="{{ mcquestion.content }} height="100" width="100"" />
         {% endif %}
		  
{% for answer in mcquestion.answer_set.all %}

  			<tr class="option_holder o4_holder">
                                </td>
                                <td class="col3">
                                    <img style="display:none;" class="option_image o4_img" />
                                    <div class="option_text o4_text">{{ answer.content }}</div>
                                </td>
                            </tr>
        {% endfor %}

<p><b>Solution: </b> {{ mcquestion.explanation }}</p>

        {% endfor %}

{% endblock %}

multichoice/templates/quiz/mathematics_subcategory_detail.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of MCQuestions" %}</h1>

        {% for mcquestion in question_list %}

  			
			  <h2>{{ mcquestion.category }}</h2>
			  <h3>{{ mcquestion.sub_category }}</h3>
			  <p>{{ mcquestion.content }}</p>
              <img src="{{ mcquestion.figure.url }}" alt="{{ mcquestion.content }}" />
			  
			  {% for answer in mcquestion.answer_set.all %}

  			
			  <p>{{ answer.content }}</p>
        {% endfor %}

<p>{{ mcquestion.explanation }}</p>

        {% endfor %}

{% endblock %}

multichoice/templates/quiz/physics_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Mathematics Subcategory" %}</h1>
        {% for subcategory in subcategory_list %}
        
<table border="1" style="width:100%">
	<td>
  			
			 <tr> <a href="/multichoice/Physics/{{ subcategory.sub_category }}">{{ subcategory.sub_category }}</a><tr>
	</td>
</table>		 	
        {% endfor %}

{% endblock %}

multichoice/templates/quiz/physics_question_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Mathematics Subcategory" %}</h1>

        {% for subcategory in subcategory_list %}

  			
			  <h2>{{ subcategory.sub_category }}</h2>
        {% endfor %}

{% endblock %}

multichoice/templates/quiz/question_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of Courses" %}</h1>

        {% for category in category_list %}

<table border="1" style="width:100%">
  <tr>
    <td><a href="/multichoice/{{ category.category }}"> {{ category.category }} </a></td>

  </tr>
</table>
			  

        {% endfor %}

{% endblock %}

multichoice/templates/quiz/quiz_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{{ quiz.title }}
{% endblock %}

{% block content %}
<h2>{{ quiz.title }}</h2>
<h3>{% trans "Category" %}: {{ quiz.category }}</h3>
{% if quiz.single_attempt %}
  <h4>{% trans "You will only get one attempt at this quiz" %}.</h4>
{% endif %}
<p>{{ quiz.description }}</p>
<p>
  <a href="{% url 'quiz_question' quiz_name=quiz.url %}">
	{% trans "Start quiz" %}
  </a>
</p>
{% endblock %}

multichoice/templates/quiz/sitting_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h2>{% trans "List of complete exams" %}</h2>
    {% if sitting_list %}

		<table class="table table-bordered table-striped">

		  <thead>
			<tr>
			  <th>{% trans "User" %}</th>
			  <th>{% trans "Quiz" %}</th>
			  <th>{% trans "Completed" %}</th>
			  <th>{% trans "Score" %}(%)</th>
			  <th></th>
			</tr>
		  </thead>

		  <tbody>
			<tr>
			  <form action="" method="GET">
				<td><input type="text" name="user_filter" /></td>
				<td><input type="text" name="quiz_filter" /></td>
				<td></td>
				<td></td>
				<td><button type="submit" class="btn btn-default">{% trans "Filter"%}</button></td>
			  </form>
			</tr>


        {% for sitting in sitting_list %}

			<tr>
			  <td>{{ sitting.user }}</td>
			  <td>{{ sitting.quiz }}</td>
			  <td>{{ sitting.end|date }}</td>
			  <td>{{ sitting.get_percent_correct }}</td>
			  <td>
				<a href="{% url 'quiz_marking_detail' pk=sitting.id %}">
				  {% trans "View details" %}
				</a>
			</tr>

        {% endfor %}

		  </tbody>

		</table>
    {% else %}
        <p>{% trans "There are no matching quizzes" %}.</p>
    {% endif %}
{% endblock %}

multichoice/templates/quiz/subcategory_question_list.html
{% extends 'index.html' %}
{% load i18n %}
{% block title %}{% trans "All Quizzes" %}{% endblock %}

{% block content %}
<h1>{% trans "List of MCQuestions" %}</h1>

        {% for mcquestion in mcquestion_list %}

  			
			  <h2>{{ mcquestion.category }}</h2>
			  <h3>{{ mcquestion.sub_category }}</h3>
			  <p>{{ mcquestion.content }}</p>
             
         {% if mcquestion.figure %}
    <img src="{{ mcquestion.figure.url }}" alt="{{ mcquestion.content }} height="100" width="100"" />
         {% endif %}
		  
{% for answer in mcquestion.answer_set.all %}

  			
			  <p>{{ answer.content }}</p>
        {% endfor %}

<p>{{ mcquestion.explanation }}</p>

        {% endfor %}

{% endblock %}