appink/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.flatpages import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^calcu/$', 'calculator.cal.views.calcu',name='calcu'),
    #url(r'^tinymce/', include('tinymce.urls')),
    #url(r'^accounts/', include('allauth.urls')),
    url(r'^multichoice/', include('multichoice.urls')),
    url(r'^q/', include('quiz.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^mathematics/', include('mathematics.urls', namespace="mathematics" )),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*?', include('mathematics.urls', namespace="mathematics" )),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
#from django.conf.urls.defaults import *
from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView
from blog.views import Myview_Tech, Myview_Product

from blog.models import Post
from.import views

urlpatterns = patterns('',
	                   url(r'^$', ListView.as_view(
	                   queryset=Post.objects.all().order_by("-date")[:10],
	                   template_name="blog_blog.html")),

	                   url(r'^(?P<pk>\d+)$', DetailView.as_view(
	                   model = Post,
	                   template_name="post.html")),

	                   #url(r'^category/Tech/$', views.get_posts, name = 'Category'),

	                   url(r'^category/Tech/$', Myview_Tech.as_view()),
	                   #queryset=Post.objects.all(),
	                   #template_name="Tech.html")),

	                   url(r'^category/Product/$', Myview_Product.as_view()),
	                   #queryset=Post.objects.all().order_by("-date")[:5],
	                   #template_name="Product.html")),
	                  )

# Create your views here.

cal/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
   url(r'^calcu/$', 'calculator.cal.views.calcu',name='calcu'),
   
)

pageink/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^mathematics/', include('mathematics.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'.*?', include('mathematics.urls')),
]

blog/models.py
from django.db import models

class Category(models.Model):
	category = models.CharField(max_length = 100)
	def __unicode__(self):
		return self.category

	def get_posts(self):
	    return Post.objects.filter(category=Tech)
# Create your models here.
class Post(models.Model):
	category = models.ForeignKey(Category)
	author = models.CharField(max_length = 100)
	title = models.CharField(max_length = 140)
	body = models.TextField()
	date = models.DateTimeField()

	def __unicode__(self):
		return self.title

physics/models.py
from django.db import models

# Create your models here.





class Question(models.Model):
	Question = models.TextField()
	#Option = models.ForeignKey(Option)
	#Hint = models.ForeignKey(Hint)
	#Solution = models.ForeignKey(Solution)


	def __unicode__(self):
		return self.Question
class Option(models.Model):
	Question = models.ForeignKey(Question)
	Option = models.TextField()

class Hint(models.Model):
	Question = models.ForeignKey(Question)
	Hint = models.TextField()

class Solution(models.Model):
	Question = models.ForeignKey(Question)
	Solution = models.TextField()

blog/views.py
from django.shortcuts import render
from blog.models import Post
from django.views.generic import ListView

class Myview_Tech(ListView):
	context_object_name ='post_list'
	queryset = Post.objects.filter(category__category = 'Tech')
	template_name = 'Tech.html'
	#context_object_name = 'post_list'
    #queryset = Post.objects.filter(category__category='Product')
    #template_name ='Tech.html'
# Create your views here.
class Myview_Product(ListView):
	context_object_name ='post_list'
	queryset = Post.objects.filter(category__category = 'Product')
	template_name = 'Tech.html'

templates/Product.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="/static/css/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->

  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Appinks</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/about-us/">About</a></li>
                <li><a href="/contact/">Contact</a></li> 
                <li class="dropdown">
                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="">Action</a></li>
                    <li><a href="">Another action</a></li>
                    <li><a href="">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="">Separated link</a></li>
                    <li><a href="">One more separated link</a></li>
                  </ul>
                </li>
                <li><p>                  </p></li>
                  <li><p>

                <head>
    <title>Search</title>
</head>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form><p/></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
{% block content %}

{% for post in object_list %}
<h3> <a href="/blog/{{post.id}}">{{ post.title }}</a></h3>
<div class = "post_meta">
    <h4>{{ post.category}}</h4>
    on {{ post.date}}, {{ user }}
</div>

<div class = "post_body">
    {{ post.body|safe|linebreaks}}
</div>

{% endfor %}
{% endblock %}

templates/Tech.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="/static/css/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->

  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Appinks</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/about-us/">About</a></li>
                <li><a href="/contact/">Contact</a></li> 
                <li class="dropdown">
                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="">Action</a></li>
                    <li><a href="">Another action</a></li>
                    <li><a href="">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="">Separated link</a></li>
                    <li><a href="">One more separated link</a></li>
                  </ul>
                </li>
                <li><p>                  </p></li>
                  <li><p>

                <head>
    <title>Search</title>
</head>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form><p/></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
{% block content %}

{% for post in object_list %}


<h3> <a href="/blog/{{post.id}}">{{ post.title }}</a></h3>
<div class = "post_meta">
    <h4>{{ post.category}}</h4>
    on {{ category.date}}, {{ user }}
</div>
<div class = "post_body">
    {{ post.body|safe|linebreaks}}
</div>

{% endfor %}
{% endblock %}

templates/archives.html
{% extends "base.html" %}
{% block content %}

{% for post in object_list %}
<p> {{post.date|date:"Y-m-d"}}<a href="/blog/{{post.id}}">{{ post.title }}</a></p>

{% endfor %}
{% endblock %}

templates/blog.html
{% extends "index.html" %}
{% block content %}

{% for question in object_list %}
<h3> <a href="{% url 'mathematics:detail' question.id %}">{{ question.Question }}</a></h3>
<div class = "post_meta">
    on {{ question.date}}

</div>
{% for option in question.option_set.all %}
{{ i  }}

{{ i }}


<div class = "post_body">
    <p>{{ option.Option_Number }}{{ option.Option|safe|linebreaks}}</p>
</div>
{% endfor %}
{% for solution in question.solution_set.all %}
<div class = "post_body">
    <p>{{ solution.Solution|safe|linebreaks}}</p>
</div>

{% endfor %}
{% endfor %}
{% endblock %}

templates/detail.html
{% extends "index.html" %}
{% block content %}

<h1>{{ question.Question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'mathematics:submit' question.id %}" method="post">
{% csrf_token %}
{% for option in question.option_set.all %}
    <input type="radio" name="option" id="option{{ forloop.counter }}" value="{{ option.id }}" />
    <label for="option{{ forloop.counter }}">{{ option.Option }}</label><br />
{% endfor %}
<input type="submit" value="Submit" />
</form>

{% endblock %}

templates/latestnews.html
{% extends "base.html" %}
{% block content %}

{% for post in object_list %}
<p> {{post.date|date:"Y-m-d"}}<a href="/blog/{{post.id}}">{{ post.title }}</a></p>

{% endfor %}
{% endblock %}

templates/post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom styles for this template -->
    <link href="/static/css/carousel.css" rel="stylesheet">
  </head>
<!-- NAVBAR
================================================== -->

  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Appinks</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="/">Home</a></li>
                <li><a href="/about-us/">About</a></li>
                <li><a href="/contact/">Contact</a></li> 
                <li class="dropdown">
                  <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="">Action</a></li>
                    <li><a href="">Another action</a></li>
                    <li><a href="">Something else here</a></li>
                    <li role="separator" class="divider"></li>
                    <li class="dropdown-header">Nav header</li>
                    <li><a href="">Separated link</a></li>
                    <li><a href="">One more separated link</a></li>
                  </ul>
                </li>
                <li><p>                  </p></li>
                  <li><p>

                <head>
    <title>Search</title>
</head>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form><p/></li>
              </ul>
            </div>
          </div>
        </nav>

      </div>
    </div>


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Example headline.</h1>
              <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous" Glyphicon buttons on the left and right might not load/display properly due to web browser security rules.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Another example headline.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>One more for good measure.</h1>
              <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
{% block content %}

<h3> <a href="/blog/{{post.id}}">{{ post.title }}</a></h3>
<div class = "post_meta">
    on {{ post.date}}
</div>

<div class = "post_body">
    {{ post.body|safe|linebreaks}}
</div>

{% endblock %}

templates/results.html
{% extends "index.html" %}
{% block content %}
{{ selected_option }}
<h1>{{ question.Question }}</h1>
<ul>
{% for option in question.option_set.all %}
    <li> {{ option.Option }}</li>
{% endfor %}
</ul>
{% for solution in question.solution_set.all %}
<div class = "post_body">
    <p>{{ solution.Solution|safe|linebreaks}}</p>
</div>
{% endfor %}
{% endblock %}

templates/search_form.html
{% extends "index.html" %}
{% block content %}

<head>
    <title>Search</title>
</head>
<body>
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
{% endblock %}

templates/search_results.html
{% extends "index.html" %}
{% block content %}

<p>You searched for: <strong>{{ query }}</strong></p>

{% if questions %}
    <p>Found {{ questions|length }} question{{ question|pluralize }}.</p>
    <ul>
        {% for question in questions %}
        <li>{{ question.Question }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}
{% endblock %}